# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client_communication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'client_communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63lient_communication.proto\"\x0e\n\x0c\x45mptyMessage\".\n\x1fPingClientCommunicationResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2a\n\x13\x43lientCommunication\x12J\n\x17PingClientCommunication\x12\r.EmptyMessage\x1a .PingClientCommunicationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYMESSAGE']._serialized_start=30
  _globals['_EMPTYMESSAGE']._serialized_end=44
  _globals['_PINGCLIENTCOMMUNICATIONRESPONSE']._serialized_start=46
  _globals['_PINGCLIENTCOMMUNICATIONRESPONSE']._serialized_end=92
  _globals['_CLIENTCOMMUNICATION']._serialized_start=94
  _globals['_CLIENTCOMMUNICATION']._serialized_end=191
# @@protoc_insertion_point(module_scope)
